export enum Configuration {
    HOST = 'HOST',
    PORT = 'PORT',
    DATABASE_HOST = 'DATABASE_HOST',
    DATABASE_PORT = 'DATABASE_PORT',
    DATABASE_USER = 'DATABASE_USER',
    DATABASE_PASS = 'DATABASE_PASS',
    DATABASE_NAME = 'DATABASE_NAME',
    DATABASE_TYPE = 'DATABASE_TYPE',
    DATABASE_TIMEZONE = 'DATABASE_TIMEZONE',
    SECRET = 'SECRET',
}
